package org.netcracker.students.servlets.constants;

public class ServletConstants {
    public static final String PARAMETER_NAME = "name";
    public static final String PARAMETER_DESCRIPTION = "description";
    public static final String PARAMETER_ACCESS_MODIFIER = "accessModifier";
    public static final String PARAMETER_LOGIN = "login";
    public static final String PARAMETER_PASSWORD = "password";
    public static final String PARAMETER_COLUMN = "column";
    public static final String PARAMETER_EQUAL = "equal";
    public static final String PARAMETER_SORT = "sort";
    public static final String PARAMETER_PATTERN = "pattern";
    public static final String ATTRIBUTE_NAME_OF_JOURNALS = "journals";
    public static final String ATTRIBUTE_NAME_OF_TASKS = "tasks";
    public static final String ATTRIBUTE_USER_ID = "userId";
    public static final String ATTRIBUTE_JOURNAL_ID = "journalId";
    public static final String ATTRIBUTE_ERROR = "error";
    public static final String PATH_TO_VIEW_JOURNALS_PAGE = "view/journals.jsp";
    public static final String PATH_TO_VIEW_TASKS_PAGE = "view/tasks.jsp";
    public static final String PATH_TO_VIEW_SIGN_UP = "view/sign_up.jsp";
    public static final String PATH_TO_VIEW_WELL = "view/well.jsp";
    public static final String PARAMETER_FILENAME = "fileName";
    public static final String PATH_TO_VIEW_START = "index.jsp";
    public static final String PARAMETER_PLANNED_DATE = "plannedDate";
    public static final String PARAMETER_JOURNAL_ID = "journalId";
    public static final String TIME_PATTERN = "yyyy-MM-dd'T'HH:mm";
    public static final String PARAMETER_IDS = "ids";
    public static final String PARAMETER_ID = "id";
    public static final String STATUS_PLANNED = "PLANNED";
    public static final String PATH_TO_SCRIPT_SQL = "jdbc/script.sql";
    public static final String ERROR_ADD_JOURNAL = "ERROR. May be you have journal with same name or try again later.";
    public static final String ERROR_ADD_USER = "ERROR. May be user with this username exists or try again later.";
    public static final String ERROR_CHECK_USER = "ERROR. Incorrect password or username";
    public static final String ERROR_ADD_TASK = "ERROR. May be you have task with same name or try again later.";
    public static final String COMMON_ERROR = "ERROR. Try again later.";
    public static final String RESP_HEADER_NAME = "Content-disposition";
    public static final String RESP_HEADER_VALUE = "attachment; filename=\"";
    public static final String FILE_EXTENSION = ".xml\"";
    public static final String NOT_ERROR_VALUE = "0";
    public static final int FIRST_POS = 0;
}
